require("core.options")
require("core.keymaps")
require("core.lsp")
require("core.plugins")

require("plugins.colorscheme")
require("plugins.fzf")
require("plugins.blink")
require("plugins.neo-tree")
require("plugins.misc")
require("plugins.lualine")
require("plugins.gitsigns")
